fix secrets
Signed-off-by: bytemare <3641580+bytemare@users.noreply.github.com>

diff --git a/.github/workflows/codecov.yaml b/.github/workflows/codecov.yaml
--- a/.github/workflows/codecov.yaml
+++ b/.github/workflows/codecov.yaml
@@ -19,7 +19,7 @@ on:
         type: string
         default: 'true'
     secrets:
-      codecov:
+      token:
         required: false
 
 permissions: {}
@@ -31,12 +31,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Ensure Codecov token is available
-        env:
-          CODECOV_TOKEN: ${{ secrets.codecov }}
-        if: ${{ env.CODECOV_TOKEN == '' }}
         run: |
-          echo "Codecov token is required when running this job." >&2
-          exit 1
+          if [ -z "${{ secrets.token }}" ]; then
+            echo "Codecov token is required when running this job." >&2
+            exit 1
+          fi
 
       - name: Harden Runner
         uses: step-security/harden-runner@92c522aaa6f53af082553dedc1596c80b71aba33
diff --git a/.github/workflows/sonarqube.yaml b/.github/workflows/sonarqube.yaml
--- a/.github/workflows/sonarqube.yaml
+++ b/.github/workflows/sonarqube.yaml
@@ -35,6 +35,13 @@ jobs:
       # Needed to upload the results to code-scanning dashboard.
       security-events: write
     steps:
+      - name: Ensure SonarQube token is available
+        run: |
+          if [ -z "${{ secrets.sonar }}" ]; then
+            echo "SonarQube token is required when running this job." >&2
+            exit 1
+          fi
+
       - name: Harden Runner
         uses: step-security/harden-runner@92c522aaa6f53af082553dedc1596c80b71aba33
         with:
@@ -60,14 +67,7 @@ jobs:
         shell: bash
         run: go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
 
-      - name: Ensure SonarQube token is available
-        if: ${{ secrets.sonar == '' }}
-        run: |
-          echo "SonarQube token is required when running this job." >&2
-          exit 1
-
       - uses: SonarSource/sonarqube-scan-action@40f5b61913e891f9d316696628698051136015be
-        if: ${{ secrets.sonar != '' }}
         env:
           GITHUB_TOKEN: ${{ secrets.github || github.token }}
           SONAR_TOKEN: ${{ secrets.sonar }}
