separate logic and add flexibility
Signed-off-by: bytemare <3641580+bytemare@users.noreply.github.com>

diff --git a/.github/workflows/codecov.yaml b/.github/workflows/codecov.yaml
--- a/.github/workflows/codecov.yaml
+++ b/.github/workflows/codecov.yaml
@@ -20,7 +20,7 @@ on:
         default: 'true'
     secrets:
       codecov:
-        required: true
+        required: false
 
 permissions: {}
 
@@ -30,6 +30,12 @@ jobs:
       fail-fast: false
     runs-on: ubuntu-latest
     steps:
+      - name: Ensure Codecov token is available
+        if: ${{ !secrets.codecov }}
+        run: |
+          echo "Codecov token is required when running this job." >&2
+          exit 1
+
       - name: Harden Runner
         uses: step-security/harden-runner@92c522aaa6f53af082553dedc1596c80b71aba33
         with:
diff --git a/.github/workflows/sonarqube.yaml b/.github/workflows/sonarqube.yaml
--- a/.github/workflows/sonarqube.yaml
+++ b/.github/workflows/sonarqube.yaml
@@ -19,9 +19,9 @@ on:
         required: true
     secrets:
       github:
-        required: true
+        required: false
       sonar:
-        required: true
+        required: false
 
 permissions: {}
 
@@ -60,9 +60,16 @@ jobs:
         shell: bash
         run: go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
 
+      - name: Ensure SonarQube token is available
+        if: ${{ !secrets.sonar }}
+        run: |
+          echo "SonarQube token is required when running this job." >&2
+          exit 1
+
       - uses: SonarSource/sonarqube-scan-action@40f5b61913e891f9d316696628698051136015be
+        if: ${{ secrets.sonar }}
         env:
-          GITHUB_TOKEN: ${{ secrets.github }}
+          GITHUB_TOKEN: ${{ secrets.github || github.token }}
           SONAR_TOKEN: ${{ secrets.sonar }}
         with:
           args: >
